/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Grafico;

import PA.LLenarfichero;
import PA.Algoritmo;
import PA.Punto;
import java.awt.Choice;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wadad
 */
public class Comparar2Estrategias extends javax.swing.JDialog {

    private final Choice[] eleccion = new Choice[2];
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public Comparar2Estrategias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (int i = 0; i < 2; i++) {
            eleccion[i] = new Choice();
            eleccion[i].setBounds(570, 20 + (30 * i), 120, 30);
            getContentPane().add(eleccion[i]);
            eleccion[i].add("--");
            eleccion[i].add("Exhaustivo");
            eleccion[i].add("Poda");
            eleccion[i].add("Divide y Venceras");
            eleccion[i].add("DyV Mejorado");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Talla", "Tiempo(msg)", "Tiempo(msg)", "Distancias", "Distancias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Volver Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Comparar Dos Estrategias");

        jLabel2.setText("elige un algoritmo");

        jLabel3.setText("elige otro algoritmo");

        jLabel4.setText("talla inicial");

        jLabel5.setText("talla final");

        jLabel6.setText("incremento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!eleccion[0].getSelectedItem().equals("--") && !eleccion[1].getSelectedItem().equals("--")) {
            Punto[] puntos;
            long[] tiempo = new long[2];
            double[] distancias = new double[2];

            if (!jTextField1.getText().equals("") && !jTextField2.getText().equals("") && Integer.parseInt(jTextField2.getText()) > Integer.parseInt(jTextField1.getText()) && !jTextField3.getText().equals("")) {
                int talla_ini = Integer.parseInt(jTextField1.getText());
                int talla_fin = Integer.parseInt(jTextField2.getText());
                int talla_incremento = Integer.parseInt(jTextField3.getText());

                long t_inicial, t_final, t_media;
                String s[] = {"Talla", "Tiempo1", "Tiempo2", "Distancia1", "Distancia2"};
                dtm.setColumnIdentifiers(s);
                for (int i = talla_ini; i <= talla_fin; i = i + talla_incremento) {
                    tiempo[0] = 0;
                    tiempo[1] = 0;
                    distancias[0] = 0;
                    distancias[1] = 0;
                    for (int j = 0; j < 10; j++) {
                        puntos = new Punto[i];
                        try {
                            LLenarfichero.generarDataSet(i, false, true);
                        } catch (IOException ex) {
                            Logger.getLogger(Comparar2Estrategias.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        for (int k = 1; k <= 2; k++) {
                            try {
                                puntos = LLenarfichero.llenarfichero("\\Estrategia4\\DataSet" + i + ".tsp");
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(Comparar2Estrategias.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            t_inicial = System.nanoTime();

                            switch (eleccion[k - 1].getSelectedItem()) {
                                case "Exhaustivo":
                                    distancias[k - 1] += Algoritmo.Exhaustivo(puntos, 0, puntos.length - 1).distancia();
                                    break;
                                case "Poda":
                                    distancias[k - 1] += Algoritmo.Bpoda(puntos, puntos.length - 1).distancia();
                                    break;
                                case "Divide y Venceras":
                                    Algoritmo.quick_sort(puntos, 0, puntos.length - 1);
                                    distancias[k - 1] += Algoritmo.DyV(puntos, 0, puntos.length - 1,0).distancia();
                                    break;
                                case "DyV Mejorado":
                                    Algoritmo.quick_sort(puntos, 0, puntos.length - 1);
                                    distancias[k - 1] += Algoritmo.AlgoritmoDyVMejorado(puntos, 0, puntos.length - 1,0).distancia();
                                    break;
                            }
                            t_final = System.nanoTime();
                            t_media = t_final - t_inicial;
                            //t_media= (t_media/1000000.0000);
                            tiempo[k - 1] = tiempo[k - 1] + t_media;
                        }
                    }
                    dtm.addRow(new Object[]{i, tiempo[0] / 1000000.0000, tiempo[1] / 1000000.0000, distancias[0], distancias[1]});
                }
                jTable1.setModel(dtm);
            } else {
                JOptionPane.showMessageDialog(null, "Deberias rellenar los campos correctamente.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Deberias Elige los algoritmos primero.");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
