/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Grafico;

import PA.Algoritmo;
import PA.Parpuntos;
import PA.Punto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wadad
 */
public class ComprobarEstrategia extends javax.swing.JDialog {

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form ComprobarE
     *
     * @param parent
     * @param modal
     */
    public ComprobarEstrategia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (Menu_PA.puntosP != null) {
            Punto[] p = Menu_PA.puntosP;
            String s[] = {"", "Punto1", "Punto2", "Distancia", "Calculadas", "Tiempo"};
            dtm.setColumnIdentifiers(s);
            long t_inicial = System.nanoTime();
            Parpuntos l = Algoritmo.Exhaustivo(p, 0, p.length - 1);
            long t_final = System.nanoTime();
            long t_medio = t_final - t_inicial;
            dtm.addRow(new Object[]{"Exhaustivo", l.getP1().toString(), l.getP2().toString(), l.distancia(), l.getCalculadas(), t_medio / 1000000.0000});

            t_inicial = System.nanoTime();
            l = Algoritmo.Bpoda(p, p.length - 1);
            t_final = System.nanoTime();
            t_medio = t_final - t_inicial;
            dtm.addRow(new Object[]{"Poda", l.getP1().toString(), l.getP2().toString(), l.distancia(), l.getCalculadas(), t_medio / 1000000.0000});

            t_inicial = System.nanoTime();
            Algoritmo.quick_sort(p, 0, p.length - 1);
            l = Algoritmo.DyV(p, 0, p.length - 1,0);
            t_final = System.nanoTime();
            t_medio = t_final - t_inicial;
            dtm.addRow(new Object[]{"DyV", l.getP1().toString(), l.getP2().toString(), l.distancia(), l.getCalculadas(), t_medio / 1000000.0000});

            t_inicial = System.nanoTime();
            Algoritmo.quick_sort(p, 0, p.length - 1);
            l = Algoritmo.AlgoritmoDyVMejorado(p, 0, p.length - 1,0);
            t_final = System.nanoTime();
            t_medio = t_final - t_inicial;
            dtm.addRow(new Object[]{"DyV Mejorado", l.getP1().toString(), l.getP2().toString(), l.distancia(), l.getCalculadas(), t_medio / 1000000.0000});
            jTable1.setModel(dtm);
             this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Deberias Cargar Puntos en memoria primero.");
            this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Volver Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Comprobar Estrategia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Punto 1", "Punto 2", "Distancia", "Calculadas", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
