/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Grafico;

import java.awt.Color;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author wadad
 */
public class Grafica_Algoritmos extends javax.swing.JDialog {

    /**
     * Creates new form Grafica_Algoritmos
     * @param parent
     * @param modal
     */
    public Grafica_Algoritmos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Plot2DPanel paint(double[] funcion, double[] y,double funcion2[],double[] y2) {
        Plot2DPanel plot = new Plot2DPanel();
        plot.setSize(800, 600);
        plot.addScatterPlot("Puntos", Color.blue, funcion, y);
        plot.addScatterPlot("Puntos", Color.red, funcion2, y2);
        plot.addLinePlot("Linea", Color.CYAN, funcion, y);
        plot.addLinePlot("Linea", Color.yellow, funcion2, y2);
        plot.setVisible(true);
        return plot;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
