/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Grafico;

import PA.Parpuntos;
import PA.Punto;
import javax.swing.*;
import java.awt.*;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author wadad
 */
public class Grafica_Puntos extends javax.swing.JDialog {

    public Grafica_Puntos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public  Plot2DPanel paint(Parpuntos l) {
        Punto[] p=Menu_PA.puntosP;
        if(p!=null){
        double x[]=new double[p.length];
         double y[]=new double[p.length];
      
        for (int i=0;i<p.length;i++) {
            x[i]=p[i].getX();
            y[i]=p[i].getY();
        }
        Plot2DPanel plot=new Plot2DPanel();
        plot.setSize(742,493);
        
        double p1[]={l.getP1().getX(),l.getP1().getY()};
        double p2[]={l.getP2().getX(),l.getP2().getY()};
        
        plot.addScatterPlot("Puntos", x,y);
        plot.addScatterPlot("Puntos distanciamin",Color.ORANGE,p1,p2 );
        plot.addLinePlot("Linea", p1,p2);
        return plot;
      }
      else{
          JOptionPane.showMessageDialog(null, "Deberias Cargar Puntos en memoria primero.");
      }
      return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
